import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FC } from "react";
import { DefaultLayout } from "~/templates/Default";

import { api, RouterOutputs } from "~/utils/api";

const Home: NextPage = () => {
  const searchQuery = api.product.search.useQuery({
    limit: 10,
    page: 1,
    term: "",
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <div className="px-4 py-6 sm:px-0">
          <div className="bg-white">
            <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
              <div className="mt-8 grid grid-cols-1 gap-y-12 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-3 xl:gap-x-8">
                {searchQuery.data?.map((product) => (
                  <ProductCard
                    key={[product.id, product.origin].join("-")}
                    {...product}
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      </DefaultLayout>
    </>
  );
};

const ProductCard: FC<RouterOutputs["product"]["search"][number]> = (props) => {
  return (
    <>
      <div className="group relative flex flex-col overflow-hidden rounded-lg border border-gray-200 bg-white">
        <div className="aspect-w-3 aspect-h-4 bg-gray-200 sm:aspect-none group-hover:opacity-75 sm:h-96">
          <img
            src={props.thumbnail}
            alt={props.name}
            className="h-full w-full object-cover object-center sm:h-full sm:w-full"
          />
        </div>
        <div className="flex flex-1 flex-col space-y-2 p-4">
          <h3 className="text-sm font-medium text-gray-900">
            <Link href={"#"}>
              <span aria-hidden="true" className="absolute inset-0" />
              {props.name}
            </Link>
          </h3>
          <p className="text-sm text-gray-500">{props.description}</p>
          <div className="flex flex-1 flex-col justify-end">
            <p className="text-sm italic text-gray-500">{""}</p>
            <p className="text-base font-medium text-gray-900">{props.price}</p>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
