import { type NextPage } from "next";
import Head from "next/head";
import { DefaultLayout } from "~/templates/Default";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <div className="px-4 py-6 sm:px-0">
          <h1>Hello</h1>
        </div>
      </DefaultLayout>
    </>
  );
};

export default Home;
