import { Menu } from "@headlessui/react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { DefaultLayout } from "~/templates/Default";
import { api } from "~/utils/api";
import { intlCurrency } from "~/utils/intl";

const OrdersPage: NextPage = () => {
  const ordersQuery = api.order.listOrders.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <div className="px-4 py-6 sm:px-0">
          <div className="bg-white">
            <div className="py-16 sm:py-24">
              <div className="mx-auto max-w-7xl sm:px-2 lg:px-8">
                <div className="mx-auto max-w-2xl px-4 lg:max-w-4xl lg:px-0">
                  <h1 className="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">
                    Histórico de pedidos
                  </h1>
                </div>
              </div>

              <div className="mt-16">
                <h2 className="sr-only">Recent orders</h2>
                <div className="mx-auto max-w-7xl sm:px-2 lg:px-8">
                  <div className="mx-auto max-w-2xl space-y-8 sm:px-4 lg:max-w-4xl lg:px-0">
                    {ordersQuery.data?.map((order) => (
                      <div
                        key={order.id}
                        className="border-t border-b border-gray-200 bg-white shadow-sm sm:rounded-lg sm:border"
                      >
                        <h3 className="sr-only">
                          Order placed on{" "}
                          <time dateTime={order.createdAt.toISOString()}>
                            {order.createdAt.toLocaleDateString()}
                          </time>
                        </h3>

                        <div className="flex items-center border-b border-gray-200 p-4 sm:grid sm:grid-cols-4 sm:gap-x-6 sm:p-6">
                          <dl className="grid flex-1 grid-cols-2 gap-x-6 text-sm sm:col-span-3 sm:grid-cols-3 lg:col-span-2">
                            <div>
                              <dt className="font-medium text-gray-900">
                                Pedido nro
                              </dt>
                              <dd className="mt-1 text-gray-500">
                                {order.id.substring(0, 10)}
                              </dd>
                            </div>

                            <div>
                              <dt className="font-medium text-gray-900">
                                Total
                              </dt>
                              <dd className="mt-1 font-medium text-gray-900">
                                {intlCurrency(order.total)}
                              </dd>
                            </div>
                          </dl>

                          <Menu
                            as="div"
                            className="relative flex justify-end lg:hidden"
                          >
                            <div className="flex items-center">
                              <Menu.Button className="-m-2 flex items-center p-2 text-gray-400 hover:text-gray-500">
                                <span className="sr-only">
                                  Options for order {order.id.substring(0, 10)}
                                </span>
                                {/* <DotsVerticalIcon className="w-6 h-6" aria-hidden="true" /> */}
                              </Menu.Button>
                            </div>
                          </Menu>

                          <div className="hidden lg:col-span-2 lg:flex lg:items-center lg:justify-end lg:space-x-4">
                            <Link
                              href={"#"}
                              className="flex items-center justify-center rounded-md border border-gray-300 bg-white py-2 px-2.5 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-slate-500 focus:ring-offset-2"
                            >
                              <span>Ver mais</span>
                              <span className="sr-only">
                                {order.id.substring(0, 10)}
                              </span>
                            </Link>
                          </div>

                          <div className="hidden pt-2 lg:col-span-3 lg:flex lg:space-x-4">
                            <span className="text-sm text-gray-800">
                              Endereço:{" "}
                              {[
                                order.address,
                                order.city,
                                order.state,
                                order.postalCode,
                              ].join(", ")}
                            </span>
                          </div>
                        </div>

                        {/* Products */}
                        <h4 className="sr-only">Items</h4>
                        <ul role="list" className="divide-y divide-gray-200">
                          {order.items.map((product) => (
                            <li key={product.id} className="p-4 sm:p-6">
                              <div className="flex items-center sm:items-start">
                                <div className="flex-1 text-sm">
                                  <div className="font-medium text-gray-900 sm:flex sm:justify-between">
                                    <h5>{product.name}</h5>
                                    <p className="mt-2 sm:mt-0">
                                      {intlCurrency(
                                        product.unitPrice as number
                                      )}
                                    </p>
                                  </div>
                                  <p className="hidden text-gray-500 sm:mt-2 sm:block">
                                    {product.description}
                                  </p>
                                </div>
                              </div>

                              <div className="mt-6 sm:flex sm:justify-between">
                                <div className="mt-6 flex w-full items-center space-x-4 divide-x divide-gray-200 border-t border-gray-200 pt-4 text-sm font-medium sm:mt-0 sm:ml-4 sm:border-none sm:pt-0">
                                  <div className="flex w-full  items-center justify-end">
                                    <Link
                                      href={`/${product.origin.substring(
                                        0,
                                        1
                                      )}/${product.ref.split("_").at(1) ?? ""}`}
                                      className="block whitespace-nowrap text-slate-600 hover:text-slate-500"
                                    >
                                      Ver produto
                                    </Link>
                                  </div>
                                </div>
                              </div>
                            </li>
                          ))}
                        </ul>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </DefaultLayout>
    </>
  );
};

export default OrdersPage;
